# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Code coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x koverXmlReport  # skipping koverVerify to not fail if the coverage has lowered
    - name: Upload coverage reports
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: build/reports/kover/report.xml
  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #  - uses: actions/checkout@v3
  #    with:
  #      # Disabling shallow clone is recommended for improving relevancy of reporting
  #      fetch-depth: 0
  #  - name: SonarCloud Scan
  #    uses: SonarSource/sonarcloud-github-action@v2.0.2
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #    with:
  #     args: >
  #        -Dsonar.organization=estivensh4-1
  #        -Dsonar.projectKey=estivensh4_aws-kmp
  #        -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/kover/report.xml
  #        -Dsonar.exclusions=tests/**
  #        -Dsonar.verbose=true
  #        -Dsonar.c.file.suffixes=-
  #        -Dsonar.cpp.file.suffixes=-
  #        -Dsonar.objc.file.suffixes=-
#