name: Test

on:
  pull_request:
    branches:
      - docs/*
  push:
    branches:
     # - docs/*

env:
  OSSH_USERNAME: ${{ secrets.OSSH_USERNAME }}
  OSSH_PASSWORD: ${{ secrets.OSSH_PASSWORD }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASS }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reemplazar constantes en archivo Kotlin
        run: |
          sed -i -e 's/private val accessKey = .*/private val accessKey = \"${{secrets.AWS_ACCESS_KEY}}\"/' -e 's/private val secretKey = .*/private val secretKey = \"${{secrets.SECRET_KEY}}\"/' aws-s3/src/commonTest/kotlin/com/estivensh4/s3/AWSS3CommonTest.kt
          cat aws-s3/src/commonTest/kotlin/com/estivensh4/s3/AWSS3CommonTest.kt
        working-directory: ${{ github.workspace }}/